name: 'Setup Node with Cache'
description: 'Sets up Node.js with caching and installs dependencies'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    - run: npm ci
      shell: bash
