name: Build and Deploy Functions

on:
  push:
    branches: [main, develop, master]
    paths:
      - 'src/functions/**'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-with-cache
        id: setup-node
      - name: Run linting
        run: npm run lint
